version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  
  minio:
    image: quay.io/minio/minio
    volumes:
      - ./docker-data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
