version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=localpass
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    volumes:
      - ./docker-data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"

volumes:
  db:
