version: '3'
services:
  minio-gw:
    image: minio/minio:RELEASE.2022-10-24T18-35-07Z
    command: gateway s3 https://bucket.allvoice.ai --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY:
      MINIO_SECRET_KEY:
