/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MqH85jSOGin
 */
import Link from "next/link"
import { Button } from "~/components/ui/button"
import { CardHeader, CardContent, Card } from "~/components/ui/card"

export default function LandingPage() {
  return (
    <div className="flex flex-col min-h-screen bg-[#f7f7f7]">
      <header className="px-4 lg:px-6 h-16 flex items-center bg-white shadow-lg">
        <Link className="flex items-center justify-center" href="#">
          <VoicemailIcon className="h-6 w-6" />
          <span className="ml-2 text-lg font-bold">VoiceAI</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Models
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Pricing
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            About
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full pt-16 md:pt-32 lg:pt-48 pb-16 bg-white">
          <div className="px-4 md:px-6 space-y-10 xl:space-y-16">
            <div className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Welcome to VoiceAI: The Marketplace for AI Voice Models
                </h1>
                <p className="mt-6 text-gray-500 md:text-xl">
                  Discover a world of AI voice models. Personalize your applications with unique voices.
                </p>
                <div className="mt-8 space-x-4">
                  <Button className="text-white bg-blue-600 hover:bg-blue-700">Get Started</Button>
                  <Link
                    className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50"
                    href="#"
                  >
                    Learn more
                  </Link>
                </div>
              </div>
              <div>
                <img
                  alt="AI voice model"
                  height="300"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "500/300",
                    objectFit: "cover",
                  }}
                  width="500"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-white">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Explore Our Top Models</h2>
              <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Hand-picked from the best in the industry. Explore our top AI voice models.
              </p>
            </div>
            <div className="mx-auto grid gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <Card>
                <CardHeader>
                  <h3 className="text-lg font-bold">Model 1</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-gray-500">Detailed description of the model.</p>
                </CardContent>
                <Button className="mt-4">Learn More</Button>
              </Card>
              <Card>
                <CardHeader>
                  <h3 className="text-lg font-bold">Model 2</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-gray-500">Detailed description of the model.</p>
                </CardContent>
                <Button className="mt-4">Learn More</Button>
              </Card>
              <Card>
                <CardHeader>
                  <h3 className="text-lg font-bold">Model 3</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-gray-500">Detailed description of the model.</p>
                </CardContent>
                <Button className="mt-4">Learn More</Button>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex items-center h-16 px-4 bg-white border-t">
        <p className="text-sm text-gray-600">© VoiceAI. All rights reserved.</p>
        <nav className="ml-auto flex gap-4">
          <Link className="text-sm hover:underline" href="#">
            Terms of Service
          </Link>
          <Link className="text-sm hover:underline" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}


function VoicemailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="6" cy="12" r="4" />
      <circle cx="18" cy="12" r="4" />
      <line x1="6" x2="18" y1="16" y2="16" />
    </svg>
  )
}
