# cluster behavior auto-redirects external http requests to https
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: allvoice-gateway
  namespace: allvoice
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: allvoice-https-certs
      hosts:
        - "allvoice.ai"
        - "*.allvoice.ai"